on: [push]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: zyborg/pester-tests-report@v1.4.0
        with:
          # include_paths: PSGitUtils.Tests
          github_token: ${{ secrets.GH_TOKEN }}
