on: [push]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: use this action, yet again
        id: testAction3
        uses: zyborg/pester-tests-report@v1.4.0
        with:
          test_results_path: copy-of-tests/test-results.nunit.xml
          report_name: TestSubsetCopy
          report_title: Copy of Subset of Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
